#!/usr/bin/env ruby

require 'dead_age_hack'

if ARGV.empty?
  print 'Usage: dead_age_hack <save.xml>'
else
  file_name = ARGV.first
  file = File.open(file_name)
  hack = DeadAgeHack.new(file)
  file.close
  hack.members.each do |member|
    member.hp = 500 if member.hp < 500
    unless member.ammo.nil?
      member.ammo = 999 if member.ammo < 999
    end
  end
  File.open(file_name, 'w').write(hack.doc)
end